/**
 * @vaaniresolve/shared — AUTHORITATIVE PUBLIC CONTRACT (declaration only).
 *
 * This file is the single source of truth for the package's public type API.
 * Consumers type-check against this surface (tsconfig paths). The declaration
 * is pinned to the current implementation and a compile-time conformance gate
 * (./conformance.ts) fails if either side drifts. Do NOT edit this file to
 * follow an implementation change — edit it to CHANGE the contract, then make
 * the implementation conform.
 *
 * Type-only package: no runtime values.
 */

/* ------------------------------------------------------------ domain types */

export type ConversationState =
  | 'IDLE'
  | 'LISTENING'
  | 'PROCESSING'
  | 'TOOL_RUNNING'
  | 'SPEAKING'
  | 'INTERRUPTED'
  | 'WAITING_CONFIRMATION'
  | 'EXECUTING_ACTION'
  | 'RESOLVED'
  | 'ERROR';

export type CommerceDomain =
  | 'order_tracking'
  | 'order_lookup'
  | 'cancellation'
  | 'returns'
  | 'refunds'
  | 'replacements'
  | 'delivery'
  | 'payment'
  | 'product_info'
  | 'warranty'
  | 'general_support';

export interface OrderItem {
  productId: string;
  name: string;
  brand: string;
  color?: string;
  quantity: number;
  price: number;
}

export type OrderStatus =
  | 'PLACED'
  | 'CONFIRMED'
  | 'PACKED'
  | 'SHIPPED'
  | 'OUT_FOR_DELIVERY'
  | 'DELIVERED'
  | 'DELAYED'
  | 'CANCELLED'
  | 'RETURN_REQUESTED'
  | 'RETURNED'
  | 'REFUNDED'
  | 'REPLACEMENT_REQUESTED';

export interface Order {
  orderId: string;
  customerId: string;
  items: OrderItem[];
  total: number;
  status: OrderStatus;
  placedAt: string;
  expectedDelivery?: string;
  deliveredAt?: string;
  carrier?: string;
  trackingNumber?: string;
  currentLocation?: string;
  cancellationEligible: boolean;
  returnEligible: boolean;
  refund?: Refund;
  address: Address;
}

export interface Address {
  name: string;
  line1: string;
  line2?: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
}

export interface Refund {
  amount: number;
  method: string;
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
  etaDays?: number;
}

export interface Product {
  productId: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  priceInr: number;
  description: string;
  inStock: boolean;
  rating: number;
  specs: Record<string, string>;
  warrantyMonths: number;
  colors: string[];
}

export interface Customer {
  customerId: string;
  name: string;
  email: string;
  phone: string;
}

export interface ToolArgument {
  name: string;
  type: 'string' | 'number' | 'boolean';
  description: string;
  required?: boolean;
  enum?: string[];
}

export interface ToolDefinition {
  name: string;
  description: string;
  domain: CommerceDomain;
  args: ToolArgument[];
  simulatedLatencyMs?: number;
  destructive?: boolean;
  failureRate?: number;
}

export interface ToolResult {
  requestId: string;
  sessionId: string;
  turnId: number;
  generation: number;
  tool: string;
  ok: boolean;
  data?: unknown;
  error?: string;
  latencyMs: number;
  stale?: boolean;
}

export interface ConfirmationRequired {
  action: string;
  tool: string;
  args: Record<string, unknown>;
  summary: string;
  orderId?: string;
  confirmationId: string;
}

export interface SpeechUtterance {
  text: string;
  cards?: ResolutionCard[];
}

export interface ResolutionCard {
  kind: 'order' | 'product' | 'shopping' | 'resolution' | 'refund' | 'delivery';
  title: string;
  subtitle?: string;
  status?: string;
  details?: Record<string, string>;
  product?: ProductCardData;
  action?: { label: string };
}

export interface ProductCardData {
  productId: string;
  name: string;
  brand: string;
  category: string;
  priceInr: number;
  rating: number;
  inStock: boolean;
  description: string;
}

/* ------------------------------------------------------------ customer care */

export interface CareSummary {
  mainProblem: string;
  conversationSummary: string;
  importantDetails: string[];
  actionsAlreadyTaken: string[];
  orderShoppingContext: string[];
  currentStatus: string;
  recommendedNextStep: string;
  customerLastAsked?: string;
}

export interface CareHandoffRequest {
  sessionId: string;
  customerName?: string;
  summary: CareSummary;
}

export interface CareHandoff extends CareHandoffRequest {
  handoffId: string;
  receivedAt: number;
  status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED';
}

/* ------------------------------------------------------------ realtime protocol */

export type ProtocolEventName =
  | 'hello'
  | 'user_speech_start'
  | 'user_speech_end'
  | 'llm_start'
  | 'llm_tokens'
  | 'tool_start'
  | 'tool_complete'
  | 'tool_stale'
  | 'user_interrupt'
  | 'generation_invalidated'
  | 'generation_bump'
  | 'confirmation_required'
  | 'confirmation_result'
  | 'state_change'
  | 'assistant_text'
  | 'rime_start'
  | 'rime_first_audio'
  | 'rime_chunk'
  | 'rime_stop'
  | 'speech_finished'
  | 'stale_result_discarded'
  | 'resolution'
  | 'response_complete'
  | 'error'
  | 'metrics';

export interface WireMessage {
  type: ProtocolEventName;
  sessionId: string;
  turnId: number;
  generation: number;
  requestId: string;
  ts: number;
  payload?: unknown;
}

export interface SessionContext {
  sessionId: string;
  turnId: number;
  generation: number;
  requestId: string;
}

export interface ClientHello {
  sessionId?: string;
  user?: { name?: string };
}

export interface ClientUserSpeech {
  transcript: string;
  final?: boolean;
  speechEndedAt?: number;
}

export interface ServerMetrics {
  sttMs?: number;
  llmMs?: number;
  rimeRequestMs?: number;
  rimeFirstAudioMs?: number;
  ttfaMs?: number;
  toolLatencyMs?: number;
  interruptCount: number;
  cancelledRequests: number;
  staleResultsDiscarded: number;
  currentState: ConversationState;
  rimeConfig: {
    provider: string;
    model: string;
    speaker: string;
    language: string;
    endpoint: string;
  };
}

export interface AssistantPayload {
  text?: string;
  cards?: ResolutionCard[];
}

export interface ConfirmationPayload extends ConfirmationRequired {}

export interface ConfirmationAnswer {
  confirmationId: string;
  accepted: boolean;
  note?: string;
}

export interface ToolEventPayload {
  tool: string;
  status: 'start' | 'complete' | 'stale' | 'cancel';
}

export interface ErrorPayload {
  code: string;
  message: string;
}

export interface ResolutionPayload {
  payload: ResolutionCard | ResolutionCard[];
}