/**
 * Synthetic demo data only. No real customer data (SECURITY).
 * Includes a Sony headphones order and a laptop order — the ambiguity the
 * interrupt/stale-result stress test relies on.
 */

import type { Customer, Order, Product } from '@vaaniresolve/shared';

const HOUR = 3600_000;
const DAY = 24 * HOUR;
const now = Date.now();
const iso = (ms: number) => new Date(ms).toISOString();

export const CUSTOMERS: Customer[] = [
  {
    customerId: 'c_asha',
    name: 'Asha Verma',
    email: 'asha.verma@example.com',
    phone: '+91 98765 43210',
  },
  {
    customerId: 'c_riya',
    name: 'Riya Menon',
    email: 'riya.menon@example.com',
    phone: '+91 91234 56789',
  },
  {
    customerId: 'c_karan',
    name: 'Karan Shah',
    email: 'karan.shah@example.com',
    phone: '+91 99887 76655',
  },
];

export const PRODUCTS: Product[] = [
  {
    productId: 'p_xm5',
    name: 'Sony WH-1000XM5 Headphones',
    brand: 'Sony',
    category: 'Headphones',
    price: 299,
    priceInr: 24990,
    description: 'Industry-leading noise cancellation with 30-hour battery.',
    inStock: true,
    rating: 4.8,
    specs: { color: 'Black', battery: '30h', noiseCancelling: 'Yes' },
    warrantyMonths: 12,
    colors: ['Black', 'Silver', 'Blue'],
  },
  {
    productId: 'p_mbp',
    name: 'MacBook Pro 14"',
    brand: 'Apple',
    category: 'Laptop',
    price: 1999,
    priceInr: 134900,
    description: 'Apple M3 chip, 14-inch Liquid Retina display, 16GB RAM.',
    inStock: true,
    rating: 4.9,
    specs: { screen: '14"', chip: 'M3', ram: '16GB' },
    warrantyMonths: 24,
    colors: ['Silver', 'Space Grey'],
  },
  {
    productId: 'p_lenovo',
    name: 'Lenovo IdeaPad Slim 5',
    brand: 'Lenovo',
    category: 'Laptop',
    price: 759,
    priceInr: 63990,
    description: 'Great value everyday laptop — 15.6" FHD, Ryzen 5, 16GB RAM.',
    inStock: true,
    rating: 4.5,
    specs: { screen: '15.6"', chip: 'Ryzen 5', ram: '16GB', weight: '1.6kg' },
    warrantyMonths: 12,
    colors: ['Grey', 'Blue'],
  },
  {
    productId: 'p_asus',
    name: 'ASUS Vivobook 15',
    brand: 'ASUS',
    category: 'Laptop',
    price: 699,
    priceInr: 58990,
    description: 'Lightweight student laptop with a fast SSD and all-day battery.',
    inStock: true,
    rating: 4.4,
    specs: { screen: '15.6"', chip: 'Intel i5', ram: '8GB', weight: '1.7kg' },
    warrantyMonths: 12,
    colors: ['Silver', 'Black'],
  },
  {
    productId: 'p_iphone',
    name: 'iPhone 15',
    brand: 'Apple',
    category: 'Phone',
    price: 799,
    priceInr: 69900,
    description: '6.1-inch Super Retina, 48MP camera, 128GB storage, USB-C.',
    inStock: true,
    rating: 4.7,
    specs: { screen: '6.1"', storage: '128GB', color: 'Blue' },
    warrantyMonths: 12,
    colors: ['Blue', 'Black', 'Pink'],
  },
  {
    productId: 'p_redmi',
    name: 'Redmi Note 13',
    brand: 'Xiaomi',
    category: 'Phone',
    price: 215,
    priceInr: 17999,
    description: 'Budget 5G all-rounder — 6.67" AMOLED, 108MP camera, 5000mAh.',
    inStock: true,
    rating: 4.5,
    specs: { screen: '6.67"', storage: '128GB', battery: '5000mAh' },
    warrantyMonths: 12,
    colors: ['Blue', 'Black', 'Green'],
  },
  {
    productId: 'p_boat',
    name: 'boAt Rockerz 550',
    brand: 'boAt',
    category: 'Headphones',
    price: 21,
    priceInr: 1749,
    description: 'Wireless over-ear headphones with 20-hour playback comfort.',
    inStock: true,
    rating: 4.3,
    specs: { battery: '20h', driver: '50mm', noiseCancelling: 'Yes' },
    warrantyMonths: 6,
    colors: ['Black', 'Blue', 'Red'],
  },
  {
    productId: 'p_watch',
    name: 'Samsung Galaxy Watch 6',
    brand: 'Samsung',
    category: 'Smartwatch',
    price: 299,
    priceInr: 29999,
    description: '40-hour battery, 5ATM water resistance, advanced health tracking.',
    inStock: true,
    rating: 4.5,
    specs: { battery: '40h', waterResistant: '5ATM' },
    warrantyMonths: 12,
    colors: ['Graphite', 'Silver'],
  },
  {
    productId: 'p_runners',
    name: 'Nike Air Zoom Pegasus 40',
    brand: 'Nike',
    category: 'Shoes',
    price: 129,
    priceInr: 6999,
    description: 'Cushioned everyday running shoe with breathable mesh upper.',
    inStock: true,
    rating: 4.6,
    specs: { size: '9 US', color: 'Black' },
    warrantyMonths: 6,
    colors: ['Black', 'White', 'Blue'],
  },
  {
    productId: 'p_kindle',
    name: 'Kindle Paperwhite',
    brand: 'Amazon',
    category: 'E-reader',
    price: 139,
    priceInr: 13999,
    description: '6.8" glare-free display, 16GB storage, weeks of battery life.',
    inStock: true,
    rating: 4.7,
    specs: { screen: '6.8"', storage: '16GB' },
    warrantyMonths: 24,
    colors: ['Black', 'Denim'],
  },
  {
    productId: 'p_s24',
    name: 'Samsung Galaxy S24',
    brand: 'Samsung',
    category: 'Phone',
    price: 799,
    priceInr: 69999,
    description: 'Compact flagship with an LTPO AMOLED, 50MP zoom camera and 7-year software support.',
    inStock: true,
    rating: 4.8,
    specs: { screen: '6.2"', chip: 'Exynos 2400', storage: '128GB', battery: '4000mAh' },
    warrantyMonths: 24,
    colors: ['Onyx Black', 'Marble Grey', 'Violet'],
  },
  {
    productId: 'p_op12r',
    name: 'OnePlus 12R',
    brand: 'OnePlus',
    category: 'Phone',
    price: 499,
    priceInr: 39999,
    description: 'Snapdragon 8 Gen 2, 5500mAh battery with 100W fast charging and a 50MP Sony camera.',
    inStock: true,
    rating: 4.6,
    specs: { screen: '6.78"', chip: 'Snapdragon 8 Gen 2', storage: '128GB', battery: '5500mAh' },
    warrantyMonths: 24,
    colors: ['Iron Grey', 'Cool Blue'],
  },
  {
    productId: 'p_nothing',
    name: 'Nothing Phone (2a)',
    brand: 'Nothing',
    category: 'Phone',
    price: 349,
    priceInr: 23999,
    description: 'Glyph-light mid-ranger with a clean Android experience and a 50MP dual rear camera.',
    inStock: true,
    rating: 4.4,
    specs: { screen: '6.7"', chip: 'Dimensity 7200 Pro', storage: '128GB', battery: '5000mAh' },
    warrantyMonths: 12,
    colors: ['Black', 'White'],
  },
  {
    productId: 'p_moto',
    name: 'Moto G84',
    brand: 'Motorola',
    category: 'Phone',
    price: 229,
    priceInr: 18999,
    description: 'Budget 5G with a vivid pOLED display and a 50MP OIS camera on a clean Android.',
    inStock: true,
    rating: 4.3,
    specs: { screen: '6.5"', chip: 'Snapdragon 695', storage: '128GB', battery: '5000mAh' },
    warrantyMonths: 12,
    colors: ['Midnight Blue', 'Viva Magenta'],
  },
  {
    productId: 'p_airpods',
    name: 'Apple AirPods Pro 2',
    brand: 'Apple',
    category: 'Headphones',
    price: 249,
    priceInr: 24999,
    description: 'Active noise cancellation with Adaptive Audio, USB-C charging and a comfortable fit.',
    inStock: true,
    rating: 4.8,
    specs: { battery: '6h ANC', noiseCancelling: 'Yes', waterResistant: 'IPX4' },
    warrantyMonths: 12,
    colors: ['White'],
  },
  {
    productId: 'p_jbl',
    name: 'JBL Tune 770NC',
    brand: 'JBL',
    category: 'Headphones',
    price: 99,
    priceInr: 4999,
    description: 'Over-ear wireless headphones with adaptive noise cancelling and 70-hour playtime.',
    inStock: true,
    rating: 4.3,
    specs: { battery: '70h', driver: '40mm', noiseCancelling: 'Yes' },
    warrantyMonths: 12,
    colors: ['Black', 'Blue', 'Sand'],
  },
  {
    productId: 'p_senn',
    name: 'Sennheiser Accentum Wireless',
    brand: 'Sennheiser',
    category: 'Headphones',
    price: 199,
    priceInr: 11990,
    description: 'Studio-tuned over-ears with hybrid ANC and a refined, premium soundstage.',
    inStock: true,
    rating: 4.5,
    specs: { battery: '50h', driver: '37mm', noiseCancelling: 'Hybrid ANC' },
    warrantyMonths: 24,
    colors: ['Black', 'White'],
  },
  {
    productId: 'p_ipad',
    name: 'iPad (10th generation)',
    brand: 'Apple',
    category: 'Tablet',
    price: 449,
    priceInr: 34900,
    description: '10.9-inch Liquid Retina iPad with an A14 chip — great for notes, movies and video calls.',
    inStock: true,
    rating: 4.7,
    specs: { screen: '10.9"', chip: 'A14 Bionic', storage: '64GB' },
    warrantyMonths: 12,
    colors: ['Blue', 'Pink', 'Silver', 'Yellow'],
  },
];

export const ORDERS: Order[] = [
  // Newest → oldest. In-flight orders deliberately land on DIFFERENT days so
  // "when will it arrive?" gives a distinct answer per order.
  {
    orderId: 'VR-88015',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_jbl',
        name: 'JBL Tune 770NC',
        brand: 'JBL',
        color: 'Black',
        quantity: 1,
        price: 99,
      },
    ],
    total: 99,
    status: 'CONFIRMED',
    placedAt: iso(now - 8 * HOUR),
    expectedDelivery: 'In about a week',
    carrier: 'BlueDart',
    trackingNumber: 'BD-4400-JBL',
    currentLocation: 'Packing at warehouse',
    cancellationEligible: true,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-66247',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_s24',
        name: 'Samsung Galaxy S24',
        brand: 'Samsung',
        color: 'Onyx Black',
        quantity: 1,
        price: 799,
      },
    ],
    total: 799,
    status: 'SHIPPED',
    placedAt: iso(now - 1 * DAY),
    expectedDelivery: 'Next Monday',
    carrier: 'Delhivery',
    trackingNumber: 'DL-7741-S24',
    currentLocation: 'Bengaluru Hub',
    cancellationEligible: true,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-55136',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_runners',
        name: 'Nike Air Zoom Pegasus 40',
        brand: 'Nike',
        color: 'Blue',
        quantity: 1,
        price: 129,
      },
    ],
    total: 129,
    status: 'SHIPPED',
    placedAt: iso(now - 30 * HOUR),
    expectedDelivery: 'In 3–4 days',
    carrier: 'Delhivery',
    trackingNumber: 'DL-0031-PEG',
    currentLocation: 'Pune Local Hub',
    cancellationEligible: true,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-11360',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_mbp',
        name: 'MacBook Pro 14"',
        brand: 'Apple',
        quantity: 1,
        price: 1999,
      },
    ],
    total: 1999,
    status: 'SHIPPED',
    placedAt: iso(now - 44 * HOUR),
    expectedDelivery: 'Tomorrow',
    carrier: 'ATS',
    trackingNumber: 'ATS-773-MBP',
    currentLocation: 'Delhi Sort Centre',
    cancellationEligible: true,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-22901',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_iphone',
        name: 'iPhone 15',
        brand: 'Apple',
        color: 'Black',
        quantity: 1,
        price: 799,
      },
    ],
    total: 799,
    status: 'OUT_FOR_DELIVERY',
    placedAt: iso(now - 2 * DAY),
    expectedDelivery: 'Day after tomorrow',
    carrier: 'Delhivery',
    trackingNumber: 'DL-9441-IP15',
    currentLocation: 'Goa Delivery Hub',
    cancellationEligible: false,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-48291',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_xm5',
        name: 'Sony WH-1000XM5 Headphones',
        brand: 'Sony',
        color: 'Black',
        quantity: 1,
        price: 299,
      },
    ],
    total: 299,
    status: 'OUT_FOR_DELIVERY',
    placedAt: iso(now - 3 * DAY),
    expectedDelivery: 'Today',
    carrier: 'Bluedart',
    trackingNumber: 'BD-88231-XM5',
    currentLocation: 'Mumbai Hub',
    cancellationEligible: false,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-77108',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_kindle',
        name: 'Kindle Paperwhite',
        brand: 'Amazon',
        quantity: 1,
        price: 139,
      },
    ],
    total: 139,
    status: 'DELAYED',
    placedAt: iso(now - 5 * DAY),
    expectedDelivery: 'Delayed — arriving by Sunday',
    carrier: 'BlueDart',
    trackingNumber: 'BD-1170-KP',
    currentLocation: 'Weather delay, Nagpur hub',
    cancellationEligible: true,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-33208',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_moto',
        name: 'Moto G84',
        brand: 'Motorola',
        color: 'Midnight Blue',
        quantity: 1,
        price: 229,
      },
    ],
    total: 229,
    status: 'CANCELLED',
    placedAt: iso(now - 10 * DAY),
    expectedDelivery: 'Cancelled',
    carrier: 'Delhivery',
    cancellationEligible: false,
    returnEligible: false,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-09744',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_iphone',
        name: 'iPhone 15',
        brand: 'Apple',
        color: 'Blue',
        quantity: 1,
        price: 799,
      },
    ],
    total: 799,
    status: 'DELIVERED',
    placedAt: iso(now - 16 * DAY),
    deliveredAt: iso(now - 14 * DAY),
    expectedDelivery: 'Delivered',
    carrier: 'BlueDart',
    cancellationEligible: false,
    returnEligible: true,
    refund: {
      amount: 799,
      method: 'UPI ••4455',
      status: 'PROCESSING',
      etaDays: 5,
    },
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-91523',
    customerId: 'c_asha',
    items: [
      {
        productId: 'p_nothing',
        name: 'Nothing Phone (2a)',
        brand: 'Nothing',
        color: 'Black',
        quantity: 1,
        price: 349,
      },
    ],
    total: 349,
    status: 'DELIVERED',
    placedAt: iso(now - 45 * DAY),
    deliveredAt: iso(now - 42 * DAY),
    expectedDelivery: 'Delivered',
    carrier: 'Bluedart',
    cancellationEligible: false,
    returnEligible: true,
    address: {
      name: 'Asha Verma',
      line1: '22 MG Road',
      city: 'Pune',
      state: 'MH',
      zip: '411001',
      phone: '+91 98765 43210',
    },
  },
  {
    orderId: 'VR-60214',
    customerId: 'c_riya',
    items: [
      {
        productId: 'p_watch',
        name: 'Samsung Galaxy Watch 6',
        brand: 'Samsung',
        color: 'Graphite',
        quantity: 1,
        price: 299,
      },
    ],
    total: 299,
    status: 'DELIVERED',
    placedAt: iso(now - 20 * DAY),
    deliveredAt: iso(now - 18 * DAY),
    expectedDelivery: 'Delivered',
    carrier: 'Delhivery',
    cancellationEligible: false,
    returnEligible: true,
    address: {
      name: 'Riya Menon',
      line1: '4 Indiranagar 100ft Road',
      city: 'Bengaluru',
      state: 'KA',
      zip: '560038',
      phone: '+91 91234 56789',
    },
  },
];

export const DEFAULT_CUSTOMER = CUSTOMERS[0];